name: Publishing image in Dockerhub
on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      IMAGE_TITLE: abekrenev-devops-final-task
    steps:
      - name: Check out Project
        uses: actions/checkout@v3

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M')"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish 
        uses: docker/build-push-action@v4 
        env:
          TAG: "${{ github.event_name == 'pull_request' && steps.date.outputs.date || github.event.release.tag_name }}"
        with:
          file: ./Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_TITLE }}:${{ env.TAG }}
          context: .
          push: true
          target: builder

