name: Run Unit Tests
on:
  push: {}
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag: 
        defualt: latest
        description: image tag

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      IMAGE_TITLE: abekrenev-devops-final-task
      TAG: ${{ github.ref_name }}
    steps:
      - name: Check out Project
        uses: actions/checkout@v3
      - name: test
        uses: ./.github/actions/test_action 
        with:
          dockerfile: ./Dockerfile
          image: ${{ env.IMAGE_TITLE }}:${{ env.TAG }}
          context: .

